services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    container_name: "database"
    environment:
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_TCP_PORT=${DB_PORT}
      - ACCEPT_EULA="Y"
    ports:
      - '1433:1433'
    volumes:
      - msql-data:/var/opt/mssql
    networks:
      - database-network

volumes:
  msql-data:
    driver: local

networks:
  database-network:
    driver: bridge