# Generated by Django 5.0.7 on 2024-08-26 04:20

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('company_name', models.CharField(max_length=500, verbose_name='Nombre Compañia')),
                ('logo', models.ImageField(upload_to='uploads', verbose_name='Logo')),
                ('url_facebook', models.URLField(blank=True, max_length=500, verbose_name='Facebook')),
                ('customer_service_email', models.EmailField(blank=True, max_length=500, verbose_name='Atencion Cliente Email')),
                ('customer_service_telephone', models.CharField(blank=True, max_length=9, verbose_name='Atencion Cliente Telefono')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Registro')),
            ],
            options={
                'verbose_name_plural': 'Info Compañia',
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('name', models.CharField(max_length=45, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('name', models.CharField(max_length=45, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_provider', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Registro')),
                ('last_update_date', models.DateTimeField(default=None, null=True, verbose_name='Fecha Actualizacion')),
                ('next_date_payment', models.DateTimeField(default=None, null=True, verbose_name='Fecha Pago')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titulo')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripcion')),
                ('image', models.ImageField(upload_to='uploads', verbose_name='Imagen')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Registro')),
                ('last_update_date', models.DateTimeField(default=None, null=True, verbose_name='Fecha Actualizacion')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=500, verbose_name='Modulo')),
                ('action', models.CharField(choices=[('01', 'Creación'), ('02', 'Actualización'), ('03', 'Eliminación')], max_length=2, verbose_name='Accion')),
                ('datetime', models.DateTimeField(verbose_name='Fecha Registro')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name_plural': 'Historial',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('name', models.CharField(max_length=45, verbose_name='Nombre')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.locality', verbose_name='Localidad')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province', verbose_name='Provincia')),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, verbose_name='Nº Orden')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fullname', models.CharField(max_length=200, verbose_name='Nombres')),
                ('email', models.CharField(max_length=100, verbose_name='Correo Electronico')),
                ('telephone', models.CharField(max_length=9, verbose_name='Telefono')),
                ('address', models.CharField(max_length=500, verbose_name='Direccion')),
                ('reference', models.URLField(max_length=500, verbose_name='Referencia')),
                ('source_detail', models.CharField(max_length=50, verbose_name='Origen Detalle')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Registro')),
                ('last_update_date', models.DateTimeField(default=None, null=True, verbose_name='Fecha Actualizacion')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city', verbose_name='Ciudad')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.locality', verbose_name='Localidad')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province', verbose_name='Provincia')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='PaymentRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Registro')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titulo')),
                ('header_tag', models.CharField(blank=True, max_length=200, verbose_name='Tag')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Descuento')),
                ('reference_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio Referencia')),
                ('main_image', models.ImageField(upload_to='uploads', verbose_name='Imagen')),
                ('show_offerts', models.BooleanField(default=True, verbose_name='Mostrar Ofertas')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Registro')),
                ('last_update_date', models.DateTimeField(default=None, null=True, verbose_name='Fecha Actualizacion')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('likes', models.IntegerField(verbose_name='Likes')),
                ('deslikes', models.IntegerField(verbose_name='Des-Likes')),
                ('starts', models.IntegerField(verbose_name='Estrellas')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Registro')),
                ('last_update_date', models.DateTimeField(default=None, null=True, verbose_name='Fecha Actualizacion')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads', verbose_name='Imagen')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titulo')),
                ('header_tag', models.CharField(blank=True, max_length=200, verbose_name='Tag')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio')),
                ('reference_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio Referencia')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Descuento')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name_plural': 'Oferta Producto',
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titulo')),
                ('values', models.JSONField(default=list)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name_plural': 'Productos Opciones',
            },
        ),
        migrations.CreateModel(
            name='ProviderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_facebook', models.URLField(blank=True, max_length=500, verbose_name='Facebook')),
                ('email', models.EmailField(blank=True, max_length=500, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=10, verbose_name='Teléfono')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Registro')),
                ('address', models.CharField(max_length=500, verbose_name='Direccion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Info Proveedor',
            },
        ),
        migrations.AddField(
            model_name='locality',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province', verbose_name='Provincia'),
        ),
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=300, verbose_name='Nombres')),
                ('email_order', models.CharField(blank=True, max_length=100, verbose_name='Correo')),
                ('telephone', models.CharField(blank=True, max_length=9, verbose_name='Telefono')),
                ('address', models.CharField(max_length=500, verbose_name='Direccion')),
                ('reference', models.CharField(max_length=500, verbose_name='Referencia')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Registro')),
                ('last_update_date', models.DateTimeField(default=None, null=True, verbose_name='Fecha Actualizacion')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city', verbose_name='Ciudad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.locality', verbose_name='Localidad')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province', verbose_name='Provincia')),
            ],
            options={
                'verbose_name_plural': 'Info Cliente',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titulo')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripcion')),
                ('main_image', models.ImageField(upload_to='uploads', verbose_name='Imagen Principal')),
                ('header_tag', models.CharField(blank=True, max_length=200, verbose_name='Tag')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio')),
                ('reference_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio Referencia')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Descuento')),
                ('show_offerts', models.BooleanField(default=True, verbose_name='Mostrar Ofertas')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Registro')),
                ('last_update_date', models.DateTimeField(default=None, null=True, verbose_name='Fecha Actualizacion')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titulo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Total')),
                ('options', models.JSONField(default=list)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Producto')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads', verbose_name='Imagen')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titulo')),
                ('header_tag', models.CharField(blank=True, max_length=200, verbose_name='Tag')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio')),
                ('reference_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio Referencia')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Descuento')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name_plural': 'Oferta Servicio',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titulo')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripcion')),
                ('image', models.ImageField(upload_to='uploads', verbose_name='Imagen')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Registro')),
                ('last_update_date', models.DateTimeField(default=None, null=True, verbose_name='Fecha Actualizacion')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Categoria')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name_plural': 'SubCategorias',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subcategory', verbose_name='SubCategory'),
        ),
    ]
