# Generated by Django 5.0.7 on 2024-08-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='next_date_payment',
        ),
        migrations.AddField(
            model_name='paymentrecords',
            name='expiration_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='Fecha Vencimiento'),
        ),
        migrations.AddField(
            model_name='paymentrecords',
            name='is_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentrecords',
            name='payment_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='Fecha Pago'),
        ),
    ]
