# Generated by Django 5.0.7 on 2024-08-31 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_customuser_next_date_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='creation_date',
        ),
    ]
