# Generated by Django 5.0.7 on 2024-09-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_customuser_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecords',
            name='expiration_date',
            field=models.DateTimeField(default=None, verbose_name='Fecha Vencimiento'),
            preserve_default=False,
        ),
    ]
