# Generated by Django 5.0.7 on 2024-09-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customuser_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='whatsapp_telephone',
            field=models.CharField(blank=True, max_length=12, verbose_name='WhatsApp Teléfono'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='customer_service_telephone',
            field=models.CharField(blank=True, max_length=12, verbose_name='Atención Cliente Teléfono'),
        ),
    ]
