# Generated by Django 5.0.7 on 2024-09-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_companyinfo_whatsapp_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='joined_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='Fecha Registro'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_update_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='providerinfo',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Direccion'),
        ),
    ]
