# Generated by Django 5.0.7 on 2024-09-23 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customuser_joined_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='subcategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='core.subcategory', verbose_name='SubCategory'),
            preserve_default=False,
        ),
    ]
