# Generated by Django 5.0.7 on 2024-09-23 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_service_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='amount',
        ),
    ]
