# Generated by Django 5.0.7 on 2024-09-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_clientinfo_district_remove_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Ciudad/Pueblo'),
            preserve_default=False,
        ),
    ]
