# Generated by Django 5.0.7 on 2024-09-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='provider_id',
            field=models.IntegerField(default=-1),
        ),
    ]
