# Generated by Django 5.0.7 on 2024-09-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_provider_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='customer_service_telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Atención Cliente Teléfono'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='whatsapp_telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp Teléfono'),
        ),
        migrations.AlterField(
            model_name='order',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='providerinfo',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
