# Generated by Django 5.0.7 on 2024-10-05 22:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_clientinfo_telephone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='Acerca de')),
                ('company', models.TextField(verbose_name='Compañia')),
                ('history', models.TextField(verbose_name='Historia')),
                ('workflow', models.TextField(verbose_name='Flujo de Trabajo')),
                ('support', models.TextField(verbose_name='Soporte')),
                ('privacy_policy', models.TextField(verbose_name='Política de Privacidad')),
                ('terms_condition', models.TextField(verbose_name='Política de Privacidad')),
            ],
            options={
                'verbose_name_plural': 'Extras',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Pregunta')),
                ('answer', models.TextField(verbose_name='Respuesta')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Registro')),
                ('last_update_date', models.DateTimeField(default=None, null=True, verbose_name='Fecha Actualizacion')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name_plural': 'FAQ',
            },
        ),
    ]
