# Generated by Django 5.0.7 on 2024-10-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_extras_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='url_instagram',
            field=models.URLField(blank=True, max_length=500, verbose_name='Instagram'),
        ),
    ]
