# Generated by Django 5.0.7 on 2024-10-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_companyinfo_url_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='service_price',
            field=models.FloatField(default=30000, verbose_name='Precio por servicio'),
        ),
        migrations.AddField(
            model_name='providerinfo',
            name='show_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Whatsapp?'),
        ),
        migrations.AddField(
            model_name='providerinfo',
            name='url_instagram',
            field=models.URLField(blank=True, max_length=500, verbose_name='Instagram'),
        ),
    ]
