# Generated by Django 5.0.7 on 2024-10-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_companyinfo_service_price_providerinfo_show_whatsapp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerinfo',
            name='show_whatsapp',
        ),
        migrations.AddField(
            model_name='providerinfo',
            name='whatsapp_telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
