# Generated by Django 5.0.7 on 2024-10-20 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_service_discount_remove_service_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='deslikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='Servicio'),
        ),
    ]
