# Generated by Django 5.0.7 on 2024-10-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerinfo',
            name='logo',
            field=models.ImageField(default='', upload_to='uploads', verbose_name='Logo'),
            preserve_default=False,
        ),
    ]
