# Generated by Django 5.0.7 on 2024-10-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_providerinfo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='available_date',
            field=models.DateField(null=True, verbose_name='Fecha Disponible'),
        ),
        migrations.AddField(
            model_name='service',
            name='with_reservation',
            field=models.BooleanField(default=False, verbose_name='Con Reservación'),
        ),
    ]
