# Generated by Django 5.0.7 on 2024-10-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_service_available_date_service_with_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='available_date',
            field=models.DateTimeField(null=True, verbose_name='Fecha Disponible'),
        ),
    ]
