# Generated by Django 5.0.7 on 2024-10-31 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_service_available_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='available_date',
        ),
        migrations.AddField(
            model_name='service',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Hora Fin'),
        ),
        migrations.AddField(
            model_name='service',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Hora Inicio'),
        ),
        migrations.AddField(
            model_name='service',
            name='weeks',
            field=models.TextField(default='', verbose_name='Semanas Disponibles'),
        ),
    ]
