# Generated by Django 5.0.7 on 2024-11-01 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_service_available_date_service_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='service',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='service',
            name='weeks',
        ),
        migrations.AddField(
            model_name='service',
            name='approximate_duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Duración Aproximada'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ServiceAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora Inicio')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora Fin')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='Servicio')),
            ],
        ),
    ]
