# Generated by Django 5.0.7 on 2024-11-02 05:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_service_end_time_remove_service_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceavailability',
            name='day',
            field=models.CharField(choices=[('MON', 'Lunes'), ('TUE', 'Martes'), ('WED', 'Miércoles'), ('THU', 'Jueves'), ('FRI', 'Viernes'), ('SAT', 'Sábado'), ('SUN', 'Domingo')], max_length=10),
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(max_length=100, verbose_name='Nº Orden')),
                ('fullname', models.CharField(max_length=200, verbose_name='Nombres')),
                ('email', models.CharField(max_length=100, verbose_name='Correo Electrónico')),
                ('telephone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('notes', models.TextField()),
                ('date', models.DateField(max_length=10, verbose_name='Fecha Reserva')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Hora Reserva')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Registro')),
                ('last_update_date', models.DateTimeField(default=None, null=True, verbose_name='Fecha Actualizacion')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name_plural': 'Reservaiones',
            },
        ),
    ]
