# Generated by Django 5.0.7 on 2024-11-02 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_serviceavailability_day_reservations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservations',
            new_name='Reservation',
        ),
    ]
