# Generated by Django 5.0.7 on 2024-11-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_reservation_active_reservation_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerinfo',
            name='company_name',
            field=models.URLField(blank=True, max_length=500, verbose_name='Nombre Empresa'),
        ),
    ]
