# Generated by Django 5.0.7 on 2024-11-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_servicedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='subservices',
            field=models.JSONField(default=list, verbose_name='Subservicios'),
        ),
    ]
